### ISSUE TITLE
Non-server users cannot use Contact forms

### ISSUE THREAD

**Issue by SakuraIsayeki** [Transan-DT/Transan.Web#18]
Logged-in users that are non-present on server are unable to submit a form in the Contact page.
Console picks up the following exception : 
```
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
       Unhandled exception in circuit 'e0w4TLry6aUogQBAcOexmbnNW973Gx1CuK2XWPCqF_4'.
       System.ApplicationException: User is not on Server.
          at Transcom.Web.Services.FormService`1.SubmitFormAsync(TForm form) in D:\Code\Source\Transcom.Web\Transcom.Web\Services\FormService.cs:line 40
          at Transcom.Web.Shared.Components.FormBaseComponent`1.OnValidFormAsync() in D:\Code\Source\Transcom.Web\Transcom.Web\Shared\Components\FormBaseComponent.razor.cs:line 50
          at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
          at Microsoft.AspNetCore.Components.Forms.EditForm.HandleSubmitAsync()
          at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
          at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

Issue should be fixed ASAP, as the contact form should be accessible to outside users, regardless of server membership.

**Comment by SakuraIsayeki** [comment]
Internal testing shows no sign of this bug, despite several reports affirming its existence. 
Leaving this fix on Hiatus for now.
